-- Migration 039: Fix agent_outputs unique index and add language tracking
--
-- Two issues from 025_agentic_foundations:
--
--   1. uq_agent_outputs_target omits the model column. Two outputs for the
--      same artifact generated by different models (e.g. Haiku vs Sonnet)
--      would silently collide. Fix: drop + recreate with model included.
--
--   2. No way to record which language codes a prompt version supports.
--      When we have dialect-aware prompts, we need to know whether the cached
--      output was generated under a dialect-aware version. Add language_supported
--      TEXT[] nullable; populated by synthesis.v2+ onwards.

BEGIN;

-- Drop old index (no data loss; just removes the constraint)
DROP INDEX IF EXISTS uq_agent_outputs_target;

-- Recreate with model column included
CREATE UNIQUE INDEX uq_agent_outputs_target
    ON agent_outputs(target_type, target_id, output_type, COALESCE(focus, ''), prompt_version, model)
    WHERE superseded_at IS NULL;

-- Track which language codes were supported at generation time.
-- NULL means "generated before language tracking existed" (pre-039).
ALTER TABLE agent_outputs
    ADD COLUMN IF NOT EXISTS language_supported TEXT[];

COMMIT;
